# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Output.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Error import Ui_errorDialog

from deep_translator import GoogleTranslator

import argostranslate.package
import argostranslate.translate


class Ui_outputDialog(object):
    def setupUi(self, outputDialog):
        outputDialog.setFixedSize(800, 600)
        outputDialog.setObjectName("outputDialog")
        self.textBox = QtWidgets.QPlainTextEdit(outputDialog)
        self.textBox.setGeometry(QtCore.QRect(10, 10, 781, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBox.sizePolicy().hasHeightForWidth())
        self.textBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBox.setFont(font)
        #self.textBox.setReadOnly(True)
        self.textBox.setObjectName("textBox")
        self.backButton = QtWidgets.QPushButton(outputDialog)
        self.backButton.setGeometry(QtCore.QRect(360, 550, 93, 28))
        self.backButton.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.backButton.setObjectName("backButton")
        self.backButton.clicked.connect(outputDialog.close)

        self.comboBox = QtWidgets.QComboBox(outputDialog)
        self.comboBox.setGeometry(QtCore.QRect(250, 260, 181, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.translateButton = QtWidgets.QPushButton(outputDialog)
        self.translateButton.setGeometry(QtCore.QRect(450, 260, 91, 31))
        self.translateButton.setObjectName("translateButton")
        self.translateButton.setEnabled(False)
        self.translateButton.clicked.connect(self.translate)
        self.comboBox.currentIndexChanged.connect(self.enable)
        self.translatedTextBox = QtWidgets.QPlainTextEdit(outputDialog)
        self.translatedTextBox.setGeometry(QtCore.QRect(10, 310, 781, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translatedTextBox.sizePolicy().hasHeightForWidth())
        self.translatedTextBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.translatedTextBox.setFont(font)
        self.translatedTextBox.setReadOnly(True)
        self.translatedTextBox.setObjectName("translatedTextBox")

        self.retranslateUi(outputDialog)
        QtCore.QMetaObject.connectSlotsByName(outputDialog)

    def enable(self):
        if self.comboBox.currentIndex != 0:
            self.translateButton.setEnabled(True)
        else:
            self.translateButton.setEnabled(False)
    def translate(self):
        to_translate = self.textBox.toPlainText()
        comboBoxValue = self.comboBox.currentText()
        tLanguage = "en"
        if self.comboBox.currentIndex() == 0:
            self.translateButton.setEnabled(False)
        elif comboBoxValue == "Hindi":
            tLanguage = "hi"
        elif comboBoxValue == "Spanish":
            tLanguage = "es"
        elif comboBoxValue == "French":
            tLanguage = "fr"
        elif comboBoxValue == "Russian":
            tLanguage = "ru"
        elif comboBoxValue == "German":
            tLanguage = "de"
        elif comboBoxValue == "Bengali":
            tLanguage = "bn"
        else:
            print("Select any language")

        from_code = "en"
        to_code = tLanguage

        try:
            # Online translation

            translated = GoogleTranslator(source='auto', target=tLanguage).translate(to_translate)
            print(translated)
            self.translatedTextBox.setPlainText(translated)

            # Offline Translation

            # Download and install Argos Translate package
            # argostranslate.package.update_package_index()
            # available_packages = argostranslate.package.get_available_packages()
            # package_to_install = next(
            #     filter(
            #         lambda x: x.from_code == from_code and x.to_code == to_code, available_packages
            #     )
            # )
            # argostranslate.package.install_from_path(package_to_install.download())
            #
            # # Translate
            # translatedText = argostranslate.translate.translate(to_translate, from_code, to_code)
            # print(translatedText)
            # self.translatedTextBox.setPlainText(translatedText)
        except:
            print("Something happened")
            self.win = QtWidgets.QDialog()
            self.ui = Ui_errorDialog()
            self.ui.setupUi(self.win)
            self.win.exec_()

        self.comboBox.setCurrentIndex(0)
        self.translateButton.setEnabled(False)


    def retranslateUi(self, outputDialog):
        _translate = QtCore.QCoreApplication.translate
        outputDialog.setWindowTitle(_translate("outputDialog", "Output"))
        self.backButton.setText(_translate("outputDialog", "Home"))
        self.comboBox.setItemText(0, _translate("outputDialog", "Select any language"))
        self.comboBox.setItemText(1, _translate("outputDialog", "Hindi"))
        self.comboBox.setItemText(2, _translate("outputDialog", "Spanish"))
        self.comboBox.setItemText(3, _translate("outputDialog", "French"))
        self.comboBox.setItemText(4, _translate("outputDialog", "Russian"))
        self.comboBox.setItemText(5, _translate("outputDialog", "German"))
        self.comboBox.setItemText(6, _translate("outputDialog", "Bengali"))
        self.translateButton.setText(_translate("outputDialog", "Translate"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    outputDialog = QtWidgets.QDialog()
    ui = Ui_outputDialog()
    ui.setupUi(outputDialog)
    outputDialog.show()
    sys.exit(app.exec_())
