# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Output.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_outputDialog(object):
    def setupUi(self, outputDialog):
        outputDialog.setObjectName("outputDialog")
        outputDialog.resize(800, 600)
        self.textBox = QtWidgets.QPlainTextEdit(outputDialog)
        self.textBox.setGeometry(QtCore.QRect(10, 10, 781, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBox.sizePolicy().hasHeightForWidth())
        self.textBox.setSizePolicy(sizePolicy)
        self.textBox.setObjectName("textBox")
        self.textBox.setReadOnly(True)
        self.backButton = QtWidgets.QPushButton(outputDialog)
        self.backButton.setGeometry(QtCore.QRect(360, 520, 93, 28))
        self.backButton.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"font: 75 11pt \"MS Shell Dlg 2\";")
        self.backButton.setObjectName("backButton")
        self.backButton.clicked.connect(outputDialog.close)

        self.retranslateUi(outputDialog)
        QtCore.QMetaObject.connectSlotsByName(outputDialog)

    def retranslateUi(self, outputDialog):
        _translate = QtCore.QCoreApplication.translate
        outputDialog.setWindowTitle(_translate("outputDialog", "Output"))
        self.backButton.setText(_translate("outputDialog", "Home"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    outputDialog = QtWidgets.QDialog()
    ui = Ui_outputDialog()
    ui.setupUi(outputDialog)
    outputDialog.show()
    sys.exit(app.exec_())
